# coding: utf-8

"""
    Pytest configuration and fixtures for vpcloud_client SDK tests.

    Generated by OpenAPI Generator (https://openapi-generator.tech)
    Do not edit the class manually.
"""  # noqa: E501

import pytest
from vpcloud_client import Configuration, ApiClient
from vpcloud_client.retry import RetryStrategy
from test.utils import create_test_config, create_test_api_client, MockResponse


@pytest.fixture
def default_config():
    """Default configuration for testing."""
    return create_test_config()


@pytest.fixture
def no_retry_config():
    """Configuration with retry disabled."""
    return create_test_config(retry_strategy=None)


@pytest.fixture
def retry_config():
    """Configuration with retry enabled."""
    return create_test_config(
        retry_strategy=RetryStrategy(max_retries=3, jitter=False)
    )


@pytest.fixture
def mock_http_response():
    """Fixture for creating mock HTTP responses."""
    return MockResponse

