# coding: utf-8

"""
    Voltage Park Cloud API

      ⚠️ **BETA PREVIEW**: This API is currently in beta and is subject to changes. Features, endpoints, request/response formats, and functionality may be modified as we continue to improve the service.      Bare Metal and VM provisioning and management service.

    The version of the OpenAPI document: 1.0.0-beta
    Contact: support@voltagepark.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FleetAppsMksCluster(BaseModel):
    """
    MK8s (managed Kubernetes) cluster information for this fleet
    """ # noqa: E501
    cluster_id: StrictStr = Field(description="MK8s cluster ID", alias="clusterId")
    cluster_name: StrictStr = Field(description="MK8s cluster name", alias="clusterName")
    installation_status: StrictStr = Field(description="MK8s installation status on the fleet", alias="installationStatus")
    cluster_status: Optional[StrictStr] = Field(default=None, description="Current MK8s cluster status", alias="clusterStatus")
    kubeconfig: Optional[StrictStr] = Field(default=None, description="The kubeconfig for accessing the cluster (if available)")
    __properties: ClassVar[List[str]] = ["clusterId", "clusterName", "installationStatus", "clusterStatus", "kubeconfig"]

    @field_validator('installation_status')
    def installation_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['CREATING', 'PROVISIONING', 'ACTIVE', 'ERROR']):
            raise ValueError("must be one of enum values ('CREATING', 'PROVISIONING', 'ACTIVE', 'ERROR')")
        return value

    @field_validator('cluster_status')
    def cluster_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CREATING', 'ACTIVE', 'UPDATING', 'DELETING', 'ERROR']):
            raise ValueError("must be one of enum values ('CREATING', 'ACTIVE', 'UPDATING', 'DELETING', 'ERROR')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FleetAppsMksCluster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FleetAppsMksCluster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clusterId": obj.get("clusterId"),
            "clusterName": obj.get("clusterName"),
            "installationStatus": obj.get("installationStatus"),
            "clusterStatus": obj.get("clusterStatus"),
            "kubeconfig": obj.get("kubeconfig")
        })
        return _obj


